/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthcheck': {
    /** @description api healthcheck */
    get: operations['getHealthCheck']
  }
  '/test': {
    /** @description get a test */
    get: operations['getTest']
    /** @description post a new test */
    post: operations['postTest']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** @default 0 */
    PaginationIndex: string
    /**
     * @default 50
     * @example 50
     */
    PaginationLimit: string
    Pagination: {
      index?: components['schemas']['PaginationIndex']
      limit?: components['schemas']['PaginationLimit']
      /** @default null */
      next?: string | null
    }
    ErrorList: {
      errors?: Array<components['schemas']['Error']>
    }
    Error: {
      /** @example Service error occured */
      description?: string
    }
    TApiTest: {
      /**
       * Format: uuid
       * @example uuid
       */
      uuid: string
      /**
       * Format: date-time
       * @example timestamp
       */
      created_at: string
    } & components['schemas']['TCreateApiTest']
    TCreateApiTest: {
      /** @example name */
      name: string
      /** @example description */
      description: string
    }
  }
  responses: {
    /** @description API endpoint not found */
    NotFound: {
      content: {
        'application/json': components['schemas']['ErrorList']
      }
    }
    /** @description Request failed with invalid request content */
    ValidationFailure: {
      content: {
        'application/json': components['schemas']['ErrorList']
      }
    }
    /** @description Request failed because of insufficient access rights */
    AccessForbiddenFailure: {
      content: {
        'application/json': components['schemas']['ErrorList']
      }
    }
    /** @description Request failed with non valid authentication data provided */
    AuthorizationFailure: {
      content: {
        'application/json': components['schemas']['ErrorList']
      }
    }
  }
  parameters: {
    queryUuidNotRequired?: string[]
    /** @description which item is the first for the page? */
    pagination_index?: components['schemas']['PaginationIndex']
    /** @description how many per page */
    pagination_limit?: components['schemas']['PaginationLimit']
  }
  requestBodies: {
    /** @description create a new test */
    PostTest?: {
      content: {
        'application/json': Array<components['schemas']['TCreateApiTest']>
      }
    }
  }
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {

  /** @description api healthcheck */
  getHealthCheck: {
    responses: {
      /** @description Successful operation */
      200: {
        content: {
          'application/json': {
            data?: {
              /** @example ok */
              uptime?: string
              /** @example ok */
              status?: string
              /** @example ok */
              version?: string
              /**
               * Format: date-time
               * @example timestamp
               */
              timestamp?: string
            }
          }
        }
      }
      404: components['responses']['NotFound']
      /** @description unexpected internal error occured */
      500: {
        content: never
      }
    }
  }
  /** @description get a test */
  getTest: {
    parameters: {
      query?: {
        ids?: components['parameters']['queryUuidNotRequired']
      }
    }
    responses: {
      /** @description Successful operation */
      200: {
        content: {
          'application/json': {
            data?: Array<components['schemas']['TApiTest']>
            _paging?: components['schemas']['Pagination']
          }
        }
      }
      400: components['responses']['ValidationFailure']
      401: components['responses']['AuthorizationFailure']
      403: components['responses']['AccessForbiddenFailure']
      404: components['responses']['NotFound']
      /** @description unexpected internal error occured */
      500: {
        content: never
      }
    }
  }
  /** @description post a new test */
  postTest: {
    requestBody: components['requestBodies']['PostTest']
    responses: {
      /** @description Successful operation */
      200: {
        content: {
          'application/json': {
            data?: Array<components['schemas']['TApiTest']>
          }
        }
      }
      400: components['responses']['ValidationFailure']
      403: components['responses']['AuthorizationFailure']
      404: components['responses']['NotFound']
      /** @description unexpected internal error occured */
      500: {
        content: never
      }
    }
  }
}
